### ISSUE TITLE
dealbot replies with HTTP status code 500

### ISSUE THREAD

**Issue by sikrew** [dealbot/dealbot#1]
Hello!

First of all, thank you for sharing this with the community!

I've followed the configuration guide thoroughly but it seems I cannot make this work, perhaps I'm doing something wrong.

I'm getting error 500 whenever a push notification is sent to dealbot on heroku. I've tried to manually create the notification channels but no cigar.

I'm not experienced at all with ruby to investigate on my own, but I've tested with [request bin](http://requestb.in/) and i get status 200 when sending pushes through that.

How can I go about debugging this?

Any help or guidance is greatly appreciated.

![pipedrive push notifications](https://cloud.githubusercontent.com/assets/10819889/19779041/4abfe08c-9c77-11e6-89e6-ddef5c33c687.png)

**Comment by sikrew** [comment]
I have narrowed it down to the configuration file. If I leave it empty, I get status 200.
But if I write my own, I'm back to the 500s.

Last thing I tried was to copy and paste the snippet that you provide in the end of the configuration documentation. But I'm still getting status 500 with that configuration.

**Comment by rossmeissl** [comment]
@sikrew sorry about that! Can you paste your configuration?

**Comment by sikrew** [comment]
Sure. Here's the config I'd like to use:

``` yaml
company: FlareKey
triggers:
  main:
    enroll:
      pipeline: 1
      stage: 2
    abandon:
      pipeline: 1
      stage: 4
    cadences:
      - 7x7
      - 5x12
```
